### ISSUE TITLE
NameError: name 'feature_contribution' is not defined

### ISSUE THREAD

**Issue by JRSlotman** [dhopp1/nowcastLSTM#10]
I'm experimenting with the variable_selection function but I get the following error:
`NameError: name 'feature_contribution' is not defined`
I've tried "univariate" instead for initial_ordering but I get a similar error. What can I do to solve this?

**Comment by dhopp1** [comment]
I believe this is because you need to not only update your R wrapper, but more importantly the Python package as well. Run `pip install nowcast-lstm==0.2.3` from the command line to update your Python package to the latest version. Hopefully this solves the issue.

**Comment by JRSlotman** [comment]
I've tried that but it still doesn't seem to work. I am using 'C:/Users/jrslo/AppData/Local/r-miniconda/' as environment. When I try to update the package in this environment, I get 
`Requirement already satisfied: nowcast-lstm==0.2.3 in c:\users\jrslo\appdata\local\r-miniconda\lib\site-packages (0.2.3)`

I've verified manually and the latest version of the package does indeed exist in the r-miniconda package library. 

All other functions work normally, except for select_model which returns the same error.

**Comment by dhopp1** [comment]
OK I see, I'll take a look at this next week, recreate the issue and hopefully find the fix.

**Comment by dhopp1** [comment]
@JRSlotman OK I've fixed the issue, it was a small bug in the pycall string interpolation from R to Python. If you reinstall nowcastLSTM with `devtools::install_github("dhopp1/nowcastLSTM")` it should work for you, let me know if this isn't the case. Thanks for identifying the issue!

**Comment by JRSlotman** [comment]
Yes, that solved the issue. Thanks!
