### ISSUE TITLE
Error in py_run_string_impl(code, local, convert) :    NameError: name 'pd' is not defined

### ISSUE THREAD

**Issue by JRSlotman** [dhopp1/nowcastLSTM#2]
Having never used Python before, I struggled a little to get the packages installed. First, PIP produced errors relating to the path length. I had to follow the steps in https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/ to proceed. Then, PIP produced warnings. This article (https://stackoverflow.com/questions/49966547/pip-10-0-1-warning-consider-adding-this-directory-to-path-or) helped me overcome that issue. 

In RStudio, the initialize_session() command initially produced errors. Turns out I had to update the Rcpp package (https://stackoverflow.com/questions/68416435/rcpp-package-doesnt-include-rcpp-precious-remove). Now I hope it finally works!

**Comment by dhopp1** [comment]
In case you haven't already figured it out, "pd" is the common short hand for the Pandas library in Python. `pip install pandas` should fix the issue, let me know if you have further troubles.
