### ISSUE TITLE
Error in `[.data.frame`(preds, , date_col) : undefined columns selected

### ISSUE THREAD

**Issue by JRSlotman** [dhopp1/nowcastLSTM#3]
After running through the test model, I've been trying out the LSTM package on my own data. I noticed that the predict function is sensitive to the name of the date column. Is that possible? The date column in my own data was capitalized so it wasn't recognized, resulting in the error above. Changing the column name to 'date' seems to do the trick.

**Comment by dhopp1** [comment]
Good spot, indeed that's a bug in the R wrapper. The Python library does not have this problem. I will fix in a future release.

**To summarize**: to ensure correct behavior of the `predict()` function on a trained model, make sure the date column of your dataframe is called exactly, `date`.
